# 监测脚本的宿主
hosts:
    Kazzak.local: # 这个是系统名称，hostname
        label: "kazzak"
    httpd-1.verycd.com: 
        label: "电信"
        dns: # 用哪些 DNS
            - 202.96.209.134
            - 202.96.209.133
    coral.xdanger.net:
        label: "网通"
    httpd-26.verycd.com:
        label: "教育网"
        dns:
            - 202.120.2.101
            - 202.120.2.100
        
targets:
    -
        url: "http://dl.verycd.com/easyMule-Setup.exe"
        bytes_range: 0..512000
        timeout: 20
    -
        url: "http://img.verycd.com/pictures/d9/5f/188241.sq.jpg"
        timeout: 4
    -
        url: "http://statics.verycd.com/javascripts/global.src.js"
        timeout: 2
    -
        url: "http://7999.com/"
        timeout: 2
    -
        url: "http://www.verycd.com/"
        timeout: 2

fanfou:
    username: xdanger@verycd.com
    password: vcalarm
